version: "3.8"
services:
  compile:
    image: golang:1.17-alpine3.15
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
      - TZ=Asia/Shanghai
      - GOOS=linux
      - GOARCH=amd64
    working_dir: /go/app
    volumes:
      - /pkg:/go/pkg
      - .:/go/app
    command: go build -o main.sh /go/app/main.go

  server:
    image: alpine:3.15
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - redis
    working_dir: /app
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    restart: always
    links:
      - redis
    command: /bin/sh -c "sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
      && apk add tzdata
      && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      && ./main.sh"

  redis:
    image: redis:6.2
    volumes:
      - ./data:/data
    expose:
      - "6379"
    restart: always
